version: '3.9'
services:
  postgresql:
    image: postgres
    restart: unless-stopped
    ports:
      - '5732:5732'

    volumes:
      - db-datase:/var/lib/postgresql/data

    networks:
      - app

    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres

  nats:
    image: nats-streaming:0.17.0
    networks:
      - app
    command:
      - '-p'
      - '4222'
      - '-m'
      - '8222'
      - '-hbi'
      - '5s'
      - '-hbt'
      - '5s'
      - '-hbf'
      - '2'
      - '-SD'
      - '-cid'
      - 'eadaming'
      - '-cluster'
      - 'nats://0.0.0.0:6222'
    ports:
      - 4222:4222
      - 8222:8222

  backend:
    image: nurettinsenbackend/testbackend
    restart: on-failure

    depends_on:
      - postgresql
      - nats
    command: sh -c "while ! nc -z postgresql 5432; do sleep 1; done && npm run dev"
    environment:
      - DB_PASS=mypassword
      - DB_HOST=postgresql
      - NATS_URL=http://nats:4222
      - COOKIE_DOMAIN=.localhost

    ports:
      - 2000:2000
    networks:
      - app

  mail:
    image: nurettinsenbackend/testmail
    restart: on-failure
    depends_on:
      - nats
    environment:
      - NATS_URL=http://nats:4222
    ports:
      - 4000:4000
    networks:
      - app

networks:
  app:
    driver: bridge
volumes:
  db-datase:
